language: node_js
node_js:
  - stable
  - lts/*
arch:
  - amd64
os: linux
dist: bionic

install:
  - npm install
before_script:
  - npm run lint
  - npm run test
script:
  - npm run build

branches:
  only:
    - master
notifications:
  email: false
